import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Build output and next-env.d.ts are generated by Next.js, not ours to lint.
    ignores: [
      ".next/**",
      ".next-build/**",
      "node_modules/**",
      "public/**",
      "scripts/**",
      "design-review/**",
      "next-env.d.ts",
    ],
  },
];

export default config;
