/**
 * The build, made loud.
 *
 * On 2026-09-04 `next build` stopped at "Linting and checking validity of
 * types ..." and exited 1 having printed nothing at all — no type error and
 * no stack. The mechanism is in Next itself (15.5, build/type-check.js): type
 * checking runs in a worker with `maxRetries: 0`, and any rejection from that
 * worker is caught by a bare `process.exit(1)`, on the stated assumption that
 * "the error is already logged in the worker". When the worker dies instead of
 * failing — killed, crashed, out of memory — nothing was logged, and the build
 * ends silently. Three traced rebuilds of the same tree, the exact failing
 * chain included, all passed; the OS recorded no crash and no memory pressure
 * at that minute. So the trigger is unknown, but the silence is Next's by
 * design, and it will happen again on any worker death.
 *
 * That leaves two duties the build never had, and this script adds them:
 *
 *   1. Type errors are checked here, first, by `tsc --noEmit --pretty`, before
 *      Next starts. A real type error is printed in full with file and line
 *      and stops the build — whatever later happens to Next's own checker.
 *      Next still checks as well; this is a second line, not a replacement.
 *   2. The outcome is verified, not taken on trust. A non-zero exit with no
 *      reason in the output is named for what it is — a process that died —
 *      rather than looking like an ordinary red build. A zero exit only counts
 *      if Next actually validated types, and actually left a fresh build
 *      behind.
 *
 * `npm run build` runs this, locally, in CI and on Vercel alike.
 */

import { spawn } from "node:child_process";
import { rm, stat } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const started = Date.now();
const bar = (s) => `\n${"=".repeat(76)}\n${s}\n${"=".repeat(76)}\n`;

function run(label, args) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, args, { cwd: ROOT, stdio: ["ignore", "pipe", "pipe"], env: process.env });
    let out = "";
    child.stdout.on("data", (d) => {
      process.stdout.write(d);
      out += d;
    });
    child.stderr.on("data", (d) => {
      process.stderr.write(d);
      out += d;
    });
    child.on("error", (err) => resolve({ code: 1, signal: null, out: `${out}\n${label} could not start: ${err.message}` }));
    child.on("close", (code, signal) => resolve({ code, signal, out }));
  });
}

/*
 * Route types under .next/types are regenerated by `next build`. Left over from
 * a previous build they can name a route that no longer exists, and tsc would
 * then fail on a file this build is about to replace. They are Next's to check.
 */
await rm(path.join(ROOT, ".next", "types"), { recursive: true, force: true });

console.log("\n[build] 1/2  types — tsc --noEmit\n");
const tsc = await run("tsc", [path.join("node_modules", "typescript", "bin", "tsc"), "--noEmit", "--pretty"]);
if (tsc.code !== 0) {
  console.error(bar(`[build] TYPE ERRORS — tsc exited ${tsc.code}. The build stops here; the errors are listed above.`));
  process.exit(1);
}
console.log("[build]      types clean");

console.log("\n[build] 2/2  next build\n");
const next = await run("next build", [path.join("node_modules", "next", "dist", "bin", "next"), "build"]);

if (/Skipping validation of types|Skipping linting/.test(next.out)) {
  console.error(bar("[build] Next skipped type validation or linting. A build that did not check does not count."));
  process.exit(1);
}

if (next.code !== 0) {
  const explained = /Failed to compile|Type error|error TS\d+|Error:|⨯|Build error occurred/.test(next.out);
  if (explained) {
    console.error(bar(`[build] next build FAILED (exit ${next.code}). The reason is printed above.`));
  } else {
    console.error(
      bar(
        `[build] next build DIED — exit ${next.code}${next.signal ? `, signal ${next.signal}` : ""}, and it printed no reason.\n` +
          "        Nothing failed that could say why: the process ended before any error\n" +
          "        reporting ran. Types were already clean (step 1), so this is not a code\n" +
          "        error. Re-run; if it repeats, run with NODE_OPTIONS=--trace-exit to see\n" +
          "        who exited, and check for anything that terminates node processes.",
      ),
    );
  }
  /* A dead worker surfaces as a nonsense code (4294967295 was measured: -1,
     unsigned). Report it above, but exit with a plain 1 — the build failed,
     and a status of -1 is not something CI or npm should have to interpret. */
  process.exit(explained && next.code ? next.code : 1);
}

/* Exit 0 only counts if the build is really there, and new. */
const fresh = async (rel) => {
  try {
    return (await stat(path.join(ROOT, ".next", rel))).mtimeMs >= started - 1000;
  } catch {
    return false;
  }
};
const checks = await Promise.all(["BUILD_ID", "routes-manifest.json", "prerender-manifest.json"].map(fresh));
if (!checks.every(Boolean) || !/Linting and checking validity of types/.test(next.out)) {
  console.error(bar("[build] next build exited 0 but did not leave a fresh, type-checked build. Not a pass."));
  process.exit(1);
}

console.log(`\n[build] verified — types checked twice (tsc, then Next), fresh build in .next, ${Math.round((Date.now() - started) / 1000)}s`);
